#!/bin/bash

podman run --rm -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -v ./scripts:/opt/jboss/startup-scripts quay.io/keycloak/keycloak:19.0.1-legacy -Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0
