musicociel:
  image: "docker.io/davdiv/musicociel"
  tag: "latest"
  replicas: 1
keycloak:
  enabled: true
  realm: "musicociel"
  client: "musicociel"
  external: false
  image: "quay.io/keycloak/keycloak"
  tag: "13.0.1"
  admin:
    username: admin
