musicociel:
  url: http://musicociel.local
  image: "docker.io/davdiv/musicociel"
  tag: "dev"
  replicas: 1
keycloak:
  enabled: true
  url: http://keycloak.local
  realm: "musicociel"
  client: "musicociel"
  external: false
  image: "docker.io/jboss/keycloak"
  tag: "13.0.1"
  admin:
    username: admin
postgresql:
  enabled: true
  image: "docker.io/library/postgres"
  tag: "13.3-alpine"
  admin:
    username: "admin"
    database: "admin"
  keycloak:
    username: "keycloak"
    database: "keycloak"
  musicociel:
    username: "musicociel"
    database: "musicociel"
  size: "8Gi"
