apiVersion: v1
entries:
  musicociel:
  - apiVersion: v2
    created: "2021-06-23T11:59:25.735839096Z"
    description: Web application to display and edit songs with lyrics and chords.
    digest: 3c9d320f6ff9348f60e1964184bcfa058fa60535606ac0aa4b74975fbb5793bf
    home: https://github.com/musicociel/musicociel#readme
    icon: https://raw.githubusercontent.com/musicociel/musicociel/dev/icon.svg
    keywords:
    - lyrics
    - chords
    - song
    - transpose-chords
    - chordpro
    - opensong
    maintainers:
    - email: divde@musicociel.fr
      name: DivDE
    name: musicociel
    sources:
    - https://github.com/musicociel/musicociel
    type: application
    urls:
    - musicociel-0.0.0.tgz
    version: 0.0.0
generated: "2021-06-23T11:59:25.734907289Z"
