apiVersion: v1
entries:
  musicociel:
  - apiVersion: v2
    created: "2021-06-09T22:20:38.785907257Z"
    description: Web application to display and edit songs with lyrics and chords.
    digest: 934e4bb5818b7f84bce8302ae8b76b02f1e0e2c0d17d4313b0c911e2da28b0d2
    home: https://github.com/musicociel/musicociel#readme
    icon: https://raw.githubusercontent.com/musicociel/musicociel/dev/icon.svg
    keywords:
    - lyrics
    - chords
    - song
    - transpose-chords
    - chordpro
    - opensong
    maintainers:
    - email: divde@musicociel.fr
      name: DivDE
    name: musicociel
    sources:
    - https://github.com/musicociel/musicociel
    type: application
    urls:
    - musicociel-0.0.0.tgz
    version: 0.0.0
generated: "2021-06-09T22:20:38.785258538Z"
