# cf https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on:
  push:
    branches: [dev]
    tags: ["*"]
  pull_request:
    branches: [dev]
jobs:
  ci:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: helm lint helm/chart --strict
      - run: npm run ui:validate
      - run: npm run jest:test
      - run: npx playwright install-deps
      - run: npx playwright install
      - run: npm run playwright:test
      - run: docker build . -t docker.io/davdiv/musicociel:local
      - run: helm package helm/chart -d helm/repository
      - name: "Load in minikube cluster"
        run: |
          minikube start --addons ingress
          minikube image load docker.io/davdiv/musicociel:local
          echo "$(minikube ip) musicociel.local keycloak.local" | sudo tee -a /etc/hosts
          helm install musicociel . --set-string musicociel.tag=local,keycloak.users[0].username=test-user,keycloak.users[0].password=test-password
        working-directory: helm/chart
      - run: npm run playwright:test
        env:
          TEST_MUSICOCIEL_URL: http://musicociel.local
          TEST_MUSICOCIEL_USERNAME: test-user
          TEST_MUSICOCIEL_PASSWORD: test-password
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: e2e/test-results/**
        if: ${{ always() }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/'))
      - name: Publish
        run: |
          export TAG="$(basename "${{ github.ref }}")"
          echo "Publish in gh-pages"
          rm -rf "./$TAG"
          cp -a ../build/public "./$TAG"
          cp -a ../helm/repository/* ./helm/
          helm repo index helm
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --allow-empty -a -m "Updating from ${{ github.sha }}"
          git push origin gh-pages
          echo "Publish in docker"
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username davdiv --password-stdin
          docker tag docker.io/davdiv/musicociel:local docker.io/davdiv/musicociel:$TAG
          docker push docker.io/davdiv/musicociel:$TAG
          docker logout
        if: github.event_name == 'push' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/'))
        working-directory: gh-pages
