# cf https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: helm lint chart --strict --set-string musicociel.url=http://musicociel.local,keycloak.url=http://keycloak.local
      - run: npm run ui:validate
      - run: npm run jest:test
      - run: docker build . -t docker.io/davdiv/musicociel:latest
      - run: minikube start --addons ingress
      - run: minikube image load docker.io/davdiv/musicociel:latest
      - run: echo "$(minikube ip) musicociel.local keycloak.local" | sudo tee -a /etc/hosts
      - run: helm install musicociel chart --set-string musicociel.url=http://musicociel.local,keycloak.url=http://keycloak.local,keycloak.admin.password=admin
      - run: TEST_MUSICOCIEL_URL=http://musicociel.local npm run jest:e2e
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Publish to Github Pages
        run: |
          rm -rf ./*
          cp -a ../build/public/* ./
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --allow-empty -a -m "Updating from ${{ github.sha }}"
          git push origin gh-pages
        working-directory: gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Publish to dockerhub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username davdiv --password-stdin &&
          docker push docker.io/davdiv/musicociel:latest &&
          docker logout
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
