# cf https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
      - run: helm lint helm/chart --strict --set-string musicociel.url=http://musicociel.local,keycloak.url=http://keycloak.local
      - run: npm run ui:validate
      - run: npm run jest:test
      - run: docker build . -t docker.io/davdiv/musicociel:local
      - name: "Load in minikube cluster"
        run: |
          minikube start --addons ingress
          minikube image load docker.io/davdiv/musicociel:local
          echo "$(minikube ip) musicociel.local keycloak.local" | sudo tee -a /etc/hosts
          helm install musicociel helm/chart --set-string musicociel.tag=local,musicociel.url=http://musicociel.local,keycloak.url=http://keycloak.local,keycloak.admin.password=admin
      - run: TEST_MUSICOCIEL_URL=http://musicociel.local npm run jest:e2e
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Publish to Github Pages
        run: |
          rm -rf ./*
          cp -a ../build/public/* ./
          cp -a ../helm/repository helm
          helm package ../helm/chart -d helm
          helm repo index helm
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit --allow-empty -a -m "Updating from ${{ github.sha }}"
          git push origin gh-pages
        working-directory: gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      - name: Publish to dockerhub
        run: |
          export TAG="$(if [ "${{ github.ref }}" == "refs/heads/main" ]; then echo latest; else basename "${{ github.ref }}"; fi)"
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username davdiv --password-stdin
          docker tag docker.io/davdiv/musicociel:local docker.io/davdiv/musicociel:$TAG
          docker push docker.io/davdiv/musicociel:$TAG
          docker logout
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
