name: okteto
on: workflow_dispatch
jobs:
  ci:
    runs-on: ubuntu-latest
    environment:
      name: okteto
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: "Deploy to okteto"
        id: deploy
        run: |
          curl https://get.okteto.com -sSfL | sh
          okteto analytics --disable
          okteto context use --token ${{ secrets.OKTETO_TOKEN }} https://cloud.okteto.com
          okteto namespace delete ${{ secrets.OKTETO_NAMESPACE }} || true
          while ! okteto namespace create ${{ secrets.OKTETO_NAMESPACE }} ; do sleep 5 ; echo "Retrying to create namespace" ; done
          okteto kubeconfig
          helm repo add musicociel https://musicociel.github.io/musicociel/helm/
          echo "url=https://musicociel${{ secrets.OKTETO_URL_SUFFIX }}" >> $GITHUB_OUTPUT
          helm install my-musicociel musicociel/musicociel --set-string musicociel.tag=dev,musicociel.url=https://musicociel${{ secrets.OKTETO_URL_SUFFIX }},keycloak.url=https://keycloak${{ secrets.OKTETO_URL_SUFFIX }},keycloak.users[0].username=demo,keycloak.users[0].password=demo
