name: update

on:
  schedule:
    - cron: "0 7 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: corepack enable
      - run: yarn set version stable
      - run: yarn up --mode=update-lockfile '**'
      - run: yarn add --mode=update-lockfile '@types/history@^4.7.9' 'history@^4.10.1'
      - run: yarn up --mode=update-lockfile -R '**'
      - name: Create pull request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          commit-message: Update dependencies
          branch: update
          title: Update dependencies
          body: Update dependencies
