name: update

on:
  schedule:
    - cron: "0 7 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npx npm-check-updates -u --peer
      - run: npm install --ignore-scripts
      - run: npm update --ignore-scripts
      - run: npm install --ignore-scripts '@types/history@^4.7.9' 'history@^4.10.1'
      - name: Create pull request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: Update dependencies
          branch: update
          title: Update dependencies
          body: Update dependencies
